In [4]:
import time

import torch
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [5]:
import torch

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print(x)
else:
    print("MPS device not found.")


tensor([1.], device='mps:0')


In [16]:
from tqdm import tqdm
import time

for i in tqdm(range(1, 100)):
    print('\r', end='')
    time.sleep(0.01)








  0%|          | 0/99 [00:00<?, ?it/s]



  9%|▉         | 9/99 [00:00<00:01, 88.22it/s]





 18%|█▊        | 18/99 [00:00<00:00, 86.06it/s]



 27%|██▋       | 27/99 [00:00<00:00, 85.19it/s]





 36%|███▋      | 36/99 [00:00<00:00, 85.44it/s]



 45%|████▌     | 45/99 [00:00<00:00, 85.32it/s]





 55%|█████▍    | 54/99 [00:00<00:00, 85.51it/s]



 64%|██████▎   | 63/99 [00:00<00:00, 84.37it/s]





 73%|███████▎  | 72/99 [00:00<00:00, 83.54it/s]



 82%|████████▏ | 81/99 [00:00<00:00, 84.33it/s]





 91%|█████████ | 90/99 [00:01<00:00, 84.90it/s]



100%|██████████| 99/99 [00:01<00:00, 84.51it/s]